import { Metadata } from 'next/types';
import ErrorPage from './ErrorPage';
export const metadata: Metadata = {
  title: '오류 페이지',
  description: 'Generated by create next app',
};
const ErrorWrap = () => {
  return <ErrorPage />;
};

export default ErrorWrap;
