version: '3.7'

services:
  app:
    image: churihyung/dagachi:latest
    ports:
      - 8090:8090
    environment:
      spring.redis.host: redis
      spring.redis.port: 6379
      spring.redis.password:
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - 6379:6379