import { Metadata } from 'next/types';
import MyPage from './MyPage';
export const metadata: Metadata = {
  title: '마이 페이지',
  description: 'Generated by create next app',
};
const MyPageWrap = () => {
  return <MyPage />;
};

export default MyPageWrap;
