spring:
  datasource:
    url: jdbc:mysql://mysql-container:3306/dagachi?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_ROOT_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL-USERNAME} #ENC(EV8C7R3Bbn0OhhOnWK6X4Cqoi8XsXrJgHoq2HirYnKw=)  # 앱 비밀번호 발급받은 google 계정
    password: ${MAIL-PASSWORD} #ENC(6ou0b1IDWg6VwICHZlYM+pSDXs4lwg0GToCxGp9wuno=)  # 발급받은 앱 비밀번호
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  data:
    redis:
      port: 6379
      host: redis
logging:
  level:
    root: info
#  config: classpath:bk_logback-spring.xml