spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: dagachi002@gmail.com #ENC(EV8C7R3Bbn0OhhOnWK6X4Cqoi8XsXrJgHoq2HirYnKw=)  # 앱 비밀번호 발급받은 google 계정
    password: tnedggdhfnnmadze #ENC(6ou0b1IDWg6VwICHZlYM+pSDXs4lwg0GToCxGp9wuno=)  # 발급받은 앱 비밀번호
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  data:
    redis:
      port: 6379
      host: localhost