import Admin from '@/app/(admin)/admin/Admin';
import { Metadata } from 'next/types';
import { Fragment } from 'react';
import Header from '@/components/Header';

export const metadata: Metadata = {
  title: '다가치 관리자 페이지',
  description: 'Generated by create next app',
};
const AdminWrap = () => {
  return (
    <Fragment>
      <Header />
      <Admin />
    </Fragment>
  );
};

export default AdminWrap;
