import { Metadata } from 'next/types';
import { Fragment } from 'react';
import Header from '@/components/Header';
import UserRegister from '@/app/(admin)/admin/userRegister/UserRegister';

export const metadata: Metadata = {
  title: '다가치 관리자 페이지 - 유저등록',
  description: 'Generated by create next app',
};
const AdminRegisterWrap = () => {
  return (
    <Fragment>
      <Header />
      <UserRegister />
    </Fragment>
  );
};

export default AdminRegisterWrap;
