///api/v1/admin/member-list

import { Metadata } from 'next/types';
import { Fragment } from 'react';
import Header from '@/components/Header';
import UserList from '@/components/UserList';
import { useTokenStore } from '@/store/useLogin';

export const metadata: Metadata = {
  title: '다가치 관리자 페이지 - 유저삭제',
  description: 'Generated by create next app',
};
const AdminDeleteWrap = async () => {

  console.log('server=====================> token :', useTokenStore.getState())
  // const resp = await http.get('api/v1/admin/member-list')
  //
  // console.log('resp:', resp)
  return (
    <Fragment>
      <Header isBackBtn={true} />
      <UserList />
    </Fragment>
  );
};

export default AdminDeleteWrap;


