///api/v1/admin/member-list

import { Metadata } from 'next/types';
import { Fragment } from 'react';
import Header from '@/components/Header';
import http from '@/services/httpService';
import UserDelete from '@/app/(admin)/admin/userDelete/UserDelete';

export const metadata: Metadata = {
  title: '다가치 관리자 페이지 - 유저삭제',
  description: 'Generated by create next app',
};
const AdminDeleteWrap = async () => {
  // const resp = await http.get('api/v1/admin/member-list')
  //
  // console.log('resp:', resp)
  return (
    <Fragment>
      <Header />
      <UserDelete />
    </Fragment>
  );
};

export default AdminDeleteWrap;


