name: build and Docker Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # JDK setting - github actions에서 사용할 JDK 설정 (프로젝트나 AWS의 java 버전과 달라도 무방)
      - uses: actions/checkout@v3
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'

      - name: Gradle Wrapper Update (Optional)
        run: ./gradlew wrapper

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Docker image
        run: docker build -t churihyung/dagachi:latest .

      - name: Tag Docker image
        run: |
          current_version=$(cat VERSION)
          docker tag churihyung/dagachi:latest churihyung/dagachi:${current_version}

      - name: Push Docker image
        run: docker push churihyung/dagachi:${current_version}